### ISSUE TITLE
user: clean up home directories after user deprovisioning

### ISSUE THREAD

**Issue by evlli** [famedly/ansible-collection-base#173]
currently user directories remain, including with the old uid. if the users change and the users get added back later, they will get a new uid, but not have the permissions to their home directory, resulting in sshd not reading from their authorized_keys breaking login.

the 2 options we have:
- delete the home directory on user deletion
- always chown home directory to current uid.

![image](https://github.com/famedly/ansible-collection-base/assets/36997087/31364d0d-bbf5-4625-b174-c936f2e07566)

**Comment by jcgruenhage** [comment]
I'm in favour of option 1.
