### ISSUE TITLE
Reload postgres config using pg_reload_conf

### ISSUE THREAD

**Issue by jcgruenhage** [famedly/ansible-collection-base#227]
Right now we're restarting postgres to reload the pg_hba, we should be using the `pg_reload_conf` function from https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SIGNAL

**Comment by blueorca363** [comment]
Seems like the handler task is the only part that must edited: https://github.com/famedly/ansible-collection-base/blob/main/roles/postgresql/handlers/main.yml

https://www.heatware.net/postgresql/postgresql-reload-config-without-restarting/

**Comment by blueorca363** [comment]
this only seems to work in some cases, though:

> The configuration file is reread whenever the main server process receives a SIGHUP signal; this signal is most easily sent by running pg_ctl reload from the command line or by calling the SQL function pg_reload_conf(). The main server process also propagates this signal to all currently running server processes, so that existing sessions also adopt the new values (this will happen after they complete any currently-executing client command). Alternatively, you can send the signal to a single server process directly. Some parameters can only be set at server start; any changes to their entries in the configuration file will be ignored until the server is restarted. Invalid parameter settings in the configuration file are likewise ignored (but logged) during SIGHUP processing.

Source: https://www.postgresql.org/docs/current/config-setting.html

**Comment by blueorca363** [comment]
As [community.postgresql.postgresql_set](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_set_module.html) uses the ALTER SYSTEM command, checking for a pending restart is quite easy:

https://dba.stackexchange.com/questions/162848/postgres-9-6-reload-or-restart-after-config-changes/262731#262731

**Comment by blueorca363** [comment]
I think this *should* work. However, I'd definitely prefer to test it somewhere before merging it.

**Comment by blueorca363** [comment]
Ready for approval.
